sudo: false

language:
  - python

python:
  - 2.7

install:
  - pip install pytest
  - pip install pomegranate
  - pip install pandas

script:
  - pytest --verbose example.py

notifications:
  email: false